import {hashSync} from "bcrypt-ts-edge";

const sampleData = {
    users:[
        {
            name: 'پارسا',
            email : 'admin@example.com',
            password: hashSync('123456',10),
            role:'admin',

        },
        {
            name: 'محسن',
            email : 'dashmosen@example.com',
            password: hashSync('123456',10),
            role:'user',

        },
    ],
    categories: [
        {
            category_id:0,
            categoryName: 'ساندویچ',
            description: 'ساندویچ های تورنج',
            categoryImage: 'https://ezteam.ir/toranj/wp-content/uploads/2024/02/image_2024-02-04_091853870.png',
        },
        {
            category_id:1,
            categoryName: 'نوشابه',
            description: 'نوشابه های تورنج',
            categoryImage: 'https://ezteam.ir/toranj/wp-content/uploads/2024/02/image_2024-02-11_162838955.png',


        },
        {
            category_id:2,
            categoryName: 'پیتزا',
            description: 'پیتزا های تورنج',
            categoryImage: 'https://ezteam.ir/toranj/wp-content/uploads/2024/02/image_2024-02-04_091917301.png',


        },
        {
            category_id:3,
            categoryName: 'مرغ',
            description: 'مرغ های تورنج',
            categoryImage: 'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_154937763.png',


        },
        {
            category_id:4,
            categoryName: 'سیب زمینی',
            description: 'سیب زمینی های تورنج',
            categoryImage: 'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_155640231.png',


        },
        {
            category_id:5,
            categoryName: 'بستنی',
            description: 'بستنی های تورنج',
            categoryImage: 'https://ezteam.ir/toranj/wp-content/uploads/2024/03/ice-cream_5089304-1.png',


        },
        {
            category_id:6,
            categoryName: 'پیش غذا',
            description: 'پیش غذا های تورنج',
            categoryImage: 'https://ezteam.ir/toranj/wp-content/uploads/2024/03/appetizer_1277756-1.png',


        },
        {
            category_id:7,
            categoryName: 'قهوه',
            description: 'قهوه های تورنج',
            categoryImage: 'https://ezteam.ir/toranj/wp-content/uploads/2024/03/coffee_648567-1.png',


        },
        {
            category_id:8,
            categoryName: 'کباب',
            description: 'کباب های تورنج',
            categoryImage: 'https://ezteam.ir/toranj/wp-content/uploads/2024/03/bbq-grill_7688706-1.png',

        },
    ],
    products:[
        {
            categoryId:0,
            productId:1,
            productName:'برگر گوشت و قارچ',
            description:'این برگر از گوشت گاو تازه و قارچ‌های تازه و خوشمزه تهیه شده است. هر برگر از این محصول حاوی حدود ۳۷۰ کیلوکالری است',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/image_2024-03-13_154624997.png',
            price:190000,
            timeOfPreparation:15,
            slug:'meat_mushroom_burger',
            discountAmount:8,
            discount: true,
        },
        {
            categoryId:0,
            productId:2,
            productName:'برگر گوشت و پنیر',
            description:'این برگر از گوشت گاو تازه و قارچ‌های تازه و خوشمزه تهیه شده است. هر برگر از این محصول حاوی حدود ۳۷۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/image_2024-03-13_154405183.png',
            price:180000,
            timeOfPreparation:15,
            slug:'meat_cheese_burger',
            discountAmount:2,
            discount: true,
        },
        {
            categoryId:0,
            productId:3,
            productName:'برگر استیک',
            description:'این برگر با استفاده از گوشت گاو تازه و آماده‌سازی به روش استیک تهیه شده است',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/image_2024-03-13_154708069.png',
            price:200000,
            timeOfPreparation:20,
            slug:'meat_burger',
            discountAmount:19,
            discount: true,
        },
        {
            categoryId:0,
            productId:4,
            productName:'برگر دودی',
            description:'این برگر با استفاده از گوشت گاو تازه و دودی شده تهیه شده است، برای بخشی از طعم معدنی خود. هر برگر از این محصول حاوی حدود ۳۸۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/image_2024-03-13_154232289.png',
            price:190000,
            timeOfPreparation:15,
            slug:'smokey_burger',
            discountAmount:0,
            discount: false,
        },
        {
            categoryId:0,
            productId:5,
            productName:'برگر دوبل',
            description:'این برگر دوبل از دو لایه گوشت گاو تازه تهیه شده است، با لایه‌های پنیر و سس مخصوص درون آن. هر برگر از این محصول حاوی حدود ۴۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/image_2024-03-13_154121100.png',
            price:180000,
            timeOfPreparation:15,
            slug:'double_burger',
            discountAmount:12,
            discount: true,
        },
        {
            categoryId:0,
            productId:6,
            productName:'برگر مخصوص',
            description:'این برگر مخصوص از گوشت گاو تازه و آماده‌سازی با ترکیبات منحصر به فرد و رسیدن به طعمی خاص تهیه شده است. هر برگر از این محصول حاوی حدود ۴۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/image_2024-03-13_154624997.png',
            price:190000,
            timeOfPreparation:35,
            slug:'meat_mushroom_burger',
            discountAmount:0,
            discount: false,
        },
        {
            categoryId:1,
            productId:7,
            productName:'نوشابه مشکی لیوانی',
            description:'این نوشابه معروف از مخلوطی از مواد طبیعی و افزودنی‌های مصنوعی تهیه شده است. هر لیوان از این نوشابه حاوی حدود ۱۵۰ کیلوکالری است',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_153132098.png',
            price:19000,
            timeOfPreparation:2,
            slug:'cup_sode',
            discountAmount:0,
            discount: false,
        },{
            categoryId:1,
            productId:8,
            productName:'نوشابه مشکی قوطی',
            description:'این نوشابه معروف از مخلوطی از مواد طبیعی و افزودنی‌های مصنوعی تهیه شده است. هر لیوان از این نوشابه حاوی حدود ۱۵۰ کیلوکالری است',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_151759387.png',
            price:29000,
            timeOfPreparation:2,
            slug:'can_sode',
            discountAmount:0,
            discount: false,
        },{
            categoryId:1,
            productId:9,
            productName:'نوشابه زیرو',
            description:'این نوشابه معروف از مخلوطی از مواد طبیعی و افزودنی‌های مصنوعی تهیه شده است. هر لیوان از این نوشابه حاوی حدود ۱۵۰ کیلوکالری است',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/image_2024-03-13_153351942.png',
            price:49000,
            timeOfPreparation:2,
            slug:'zero_sode',
            discountAmount:22,
            discount: true,
        },{
            categoryId:1,
            productId:10,
            productName:'نوشابه کوکاکولا شیشه ای',
            description:'این نوشابه معروف از مخلوطی از مواد طبیعی و افزودنی‌های مصنوعی تهیه شده است. هر لیوان از این نوشابه حاوی حدود ۱۵۰ کیلوکالری است',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/image_2024-03-13_153507535.png',
            price:34000,
            timeOfPreparation:2,
            slug:'bottle_sode',
            discountAmount:6,
            discount: true,
        },{
            categoryId:1,
            productId:11,
            productName:'نوشابه کوکاکولا',
            description:'این نوشابه معروف از مخلوطی از مواد طبیعی و افزودنی‌های مصنوعی تهیه شده است. هر لیوان از این نوشابه حاوی حدود ۱۵۰ کیلوکالری است',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/image_2024-03-13_153759908.png',
            price:34000,
            timeOfPreparation:2,
            slug:'big_sode',
            discountAmount:0,
            discount: false,
        },
        {
            categoryId:2,
            productId:12,
            productName:'پیتزا گوشت و قارچ',
            description:'پیتزا گوشت و قارچ توضیحات: این پیتزا با استفاده از خمیر تازه و رویه‌ای شامل گوشت و قارچ تهیه شده است. هر برش از این پیتزا حاوی حدود ۳۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_151431070.png',
            price:199000,
            timeOfPreparation:25,
            slug:'meat_mushroom_pizza',
            discountAmount:20,
            discount: true,
        },
        {
            categoryId:2,
            productId:13,
            productName:'پیتزا ژامبون',
            description:'پیتزا ژامبون توضیحات: این پیتزا با استفاده از خمیر تازه و رویه‌ای شامل ژامبون و مواد افزودنی دیگر تهیه شده است. هر برش از این پیتزا حاوی حدود ۳۲۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_151344813.png',
            price:249000,
            timeOfPreparation:25,
            slug:'zhambon_pizza',
            discountAmount:12,
            discount: true,
        },
        {
            categoryId:2,
            productId:14,
            productName:'پیتزا رست بیف',
            description:'این پیتزا با استفاده از خمیر تازه و رویه‌ای شامل گوشت بیف و مواد افزودنی دیگر تهیه شده است. هر برش از این پیتزا حاوی حدود ۳۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_151242508.png',
            price:259000,
            timeOfPreparation:25,
            slug:'roast_beef_pizza',
            discountAmount:8,
            discount: true,
        },
        {
            categoryId:2,
            productId:15,
            productName:'پیتزا مخلوط',
            description:'این پیتزا شامل ترکیبی از مواد مختلف از جمله گوشت، قارچ، فلفل دلمه، زیتون',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_151148631.png',
            price:199000,
            timeOfPreparation:25,
            slug:'zhambon_pizza',
            discountAmount:8,
            discount: false,
        },
        {
            categoryId:2,
            productId:16,
            productName:'پیتزا گوشت',
            description:'این پیتزا با استفاده از خمیر تازه و رویه‌ای شامل گوشت و مواد افزودنی دیگر تهیه شده است. هر برش از این پیتزا حاوی حدود ۳۰۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_150947429.png',
            price:259000,
            timeOfPreparation:25,
            slug:'meat_pizza',
            discountAmount:8,
            discount: true,
        },
        {
            categoryId:2,
            productId:17,
            productName:'پیتزا گوشت سافاری',
            description:'این پیتزا شامل ترکیبی از گوشت گاو و مواد افزودنی دیگر است، با طعم و احساسی ماجراجویانه. هر برش از این پیتزا حاوی حدود ۳۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/02/image_2024-02-04_093321534-removebg-preview-1.png',
            price:239000,
            timeOfPreparation:25,
            slug:'meat_safari_pizza',
            discountAmount:17,
            discount: true,
        },
        {
            categoryId:3,
            productId:18,
            productName:'مرغ سوخاری خانواده',
            description:'این محصول از مرغ تازه و کیفیتی برتر تهیه شده است و پس از سوختن در روغن گرم، پوست آن به‌صورت طلایی و خوشمزه شده است. هر بخش از این مرغ سوخاری حاوی حدود ۲۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_155320588.png',
            price:299000,
            timeOfPreparation:45,
            slug:'family_fried_chicken',
            discountAmount:5,
            discount: true,
        },
        {
            categoryId:3,
            productId:19,
            productName:'مرغ سوخاری',
            description:'این محصول از مرغ تازه و کیفیتی برتر تهیه شده است و پس از سوختن در روغن گرم، پوست آن به‌صورت طلایی و خوشمزه شده است. هر بخش از این مرغ سوخاری حاوی حدود ۲۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_155250803.png',
            price:299000,
            timeOfPreparation:45,
            slug:'fried_chicken',
            discountAmount:5,
            discount: true,
        },
        {
            categoryId:3,
            productId:20,
            productName:'مرغ سوخاری تک نفره',
            description:'این محصول از مرغ تازه و کیفیتی برتر تهیه شده است و پس از سوختن در روغن گرم، پوست آن به‌صورت طلایی و خوشمزه شده است. هر بخش از این مرغ سوخاری حاوی حدود ۲۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_155205462.png',
            price:279000,
            timeOfPreparation:45,
            slug:'fried_chicken_solo',
            discountAmount:16,
            discount: true,
        },
        {
            categoryId:3,
            productId:21,
            productName:'مرغ شکم پر',
            description:'این محصول از مرغ تازه و کیفیتی برتر تهیه شده است و پس از سوختن در روغن گرم، پوست آن به‌صورت طلایی و خوشمزه شده است. هر بخش از این مرغ سوخاری حاوی حدود ۲۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_155025779.png',
            price:299000,
            timeOfPreparation:45,
            slug:'fried_chicken_filled',
            discountAmount:5,
            discount: true,
        },
        {
            categoryId:3,
            productId:22,
            productName:'سینی سیب زمینی و مرغ',
            description:'این سینی شامل سیب زمینی‌های سرخ شده و قطعات مرغ تازه است. هر سرو از این سینی حاوی حدود ۴۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_155025779.png',
            price:299000,
            timeOfPreparation:35,
            slug:'fried_chicken_potato',
            discountAmount:5,
            discount: false,
        },
        {
            categoryId:4,
            productId:23,
            productName:'پک بزرگ سیب زمینی',
            description:'این پک شامل سیب زمینی‌های تازه و تهیه‌شده با روش سرخ کردن عمیق است. هر پک از این محصول حاوی حدود ۳۰۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_160630271.png',
            price:79000,
            timeOfPreparation:10,
            slug:'fries_big',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:4,
            productId:24,
            productName:'پک متوسط سیب زمینی',
            description:'این پک شامل سیب زمینی‌های تازه و تهیه‌شده با روش سرخ کردن عمیق است. هر پک از این محصول حاوی حدود ۳۰۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_160543519.png',
            price:49000,
            timeOfPreparation:10,
            slug:'fries_medium',
            discountAmount:13,
            discount: false,
        },
        {
            categoryId:4,
            productId:25,
            productName:'پک کوچک سیب زمینی',
            description:'این پک شامل سیب زمینی‌های تازه و تهیه‌شده با روش سرخ کردن عمیق است. هر پک از این محصول حاوی حدود ۳۰۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-13_160455831.png',
            price:29000,
            timeOfPreparation:10,
            slug:'fries_small',
            discountAmount:14,
            discount: true,
        },
        {
            categoryId:4,
            productId:26,
            productName:'سینی سیب زمینی و مرغ',
            description:'این سینی شامل سیب زمینی‌های سرخ شده و قطعات مرغ تازه است. هر سرو از این سینی حاوی حدود ۴۵۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/top-view-chicken-wings-chicken-wings-fried-potatoes-onion-herbs-table-1.png',
            price:360000,
            timeOfPreparation:10,
            slug:'fries_chicken',
            discountAmount:14,
            discount: false,
        },
        {
            categoryId:8,
            productId:27,
            productName:'چلو کباب شامی',
            description:'این غذا از گوشت گوسفندی تازه و کباب شده به همراه چلو تهیه شده است. هر وعده از این غذا حاوی حدود ۵۰۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/top-view-delicious-meat-cutlets-with-onion-rings-2.png',
            price:360000,
            timeOfPreparation:50,
            slug:'chelo_shami',
            discountAmount:14,
            discount: false,
        },
        {
            categoryId:8,
            productId:28,
            productName:'کباب شامی و سبزیجات',
            description:'این غذا از گوشت گوسفندی تازه و کباب شده به همراه چلو تهیه شده است. هر وعده از این غذا حاوی حدود ۵۰۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/top-view-delicious-meat-cutlets-with-fresh-salad-1.png',
            price:360000,
            timeOfPreparation:35,
            slug:'shami_vegtables',
            discountAmount:14,
            discount: false,
        },
        {
            categoryId:8,
            productId:29,
            productName:'چلو کباب',
            description:'این غذا از گوشت گوسفندی تازه و کباب شده به همراه برنج چلو تهیه شده است. هر وعده از این غذا حاوی حدود ۶۰۰ کیلوکالری است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/image_2024-03-13_161325249.png',
            price:360000,
            timeOfPreparation:35,
            slug:'chelo_kabab',
            discountAmount:14,
            discount: false,
        },
        {
            categoryId:5,
            productId:30,
            productName:'بستنی ظرفی شکلاتی',
            description:'بستنی اصلی ما با تنوع طعم‌ها و کیفیت برتر، همراه با اطلاعات کالری و لذتی بی‌نظیر، تجربه‌ای لذت‌بخش برای همه سلیقه‌ها فراهم می‌کند.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_151611404-removebg-preview.png',
            price:79000,
            timeOfPreparation:35,
            slug:'chocolate_iceCream_cup',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:5,
            productId:31,
            productName:'بستنی قیفی شکلاتی',
            description:'بستنی اصلی ما با تنوع طعم‌ها و کیفیت برتر، همراه با اطلاعات کالری و لذتی بی‌نظیر، تجربه‌ای لذت‌بخش برای همه سلیقه‌ها فراهم می‌کند.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_144730055.png',
            price:79000,
            timeOfPreparation:10,
            slug:'chocolate_iceCream_qif',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:5,
            productId:32,
            productName:'بستنی شکلات کارامل',
            description:'بستنی اصلی ما با تنوع طعم‌ها و کیفیت برتر، همراه با اطلاعات کالری و لذتی بی‌نظیر، تجربه‌ای لذت‌بخش برای همه سلیقه‌ها فراهم می‌کند.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_144839962.png',
            price:79000,
            timeOfPreparation:10,
            slug:'chocolate_iceCream_caramel',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:5,
            productId:33,
            productName:'پک بسته بندی شده شکلاتی',
            description:'بستنی اصلی ما با تنوع طعم‌ها و کیفیت برتر، همراه با اطلاعات کالری و لذتی بی‌نظیر، تجربه‌ای لذت‌بخش برای همه سلیقه‌ها فراهم می‌کند.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_144556295.png',
            price:79000,
            timeOfPreparation:10,
            slug:'chocolate_iceCream_pack',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:5,
            productId:34,
            productName:'بستنی قیفی توت فرنگی',
            description:'بستنی اصلی ما با تنوع طعم‌ها و کیفیت برتر، همراه با اطلاعات کالری و لذتی بی‌نظیر، تجربه‌ای لذت‌بخش برای همه سلیقه‌ها فراهم می‌کند.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_144453305.png',
            price:79000,
            timeOfPreparation:10,
            slug:'strawBerry_iceCream_caramel',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:6,
            productId:35,
            productName:'سوپ سبزیجات',
            description:'پیش‌غذاهای متنوع و لذیذ، همراه با طعم و کیفیت برتر، تجربه‌ای شگفت‌انگیز و لذت‌بخش برای آغازی خوش از وعده غذایی شما.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_150119034.png',
            price:79000,
            timeOfPreparation:10,
            slug:'vegetable_soup',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:6,
            productId:36,
            productName:'سالاد سبزیجات',
            description:'پیش‌غذاهای متنوع و لذیذ، همراه با طعم و کیفیت برتر، تجربه‌ای شگفت‌انگیز و لذت‌بخش برای آغازی خوش از وعده غذایی شما.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_145936647.png',
            price:79000,
            timeOfPreparation:10,
            slug:'vegetable_salad',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:6,
            productId:37,
            productName:'ژله توت فرنگی همراه با خامه',
            description:'پیش‌غذاهای متنوع و لذیذ، همراه با طعم و کیفیت برتر، تجربه‌ای شگفت‌انگیز و لذت‌بخش برای آغازی خوش از وعده غذایی شما.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_145731594.png',
            price:79000,
            timeOfPreparation:10,
            slug:'strawBerry_jelly',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:6,
            productId:38,
            productName:'خوشت ماست 250 گرمی',
            description:'پیش‌غذاهای متنوع و لذیذ، همراه با طعم و کیفیت برتر، تجربه‌ای شگفت‌انگیز و لذت‌بخش برای آغازی خوش از وعده غذایی شما.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_145445258.png',
            price:79000,
            timeOfPreparation:10,
            slug:'vegetable_soup',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:7,
            productId:39,
            productName:'قهوه دابل',
            description:'قهوه اصلی ما با برندهای معتبر و طعم‌های متنوع، رویایی برای عاشقان قهوه و لذت بخش برای همه است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_151340410.png',
            price:79000,
            timeOfPreparation:10,
            slug:'coffee_double',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:7,
            productId:40,
            productName:'قهوه برزیلی',
            description:'قهوه اصلی ما با برندهای معتبر و طعم‌های متنوع، رویایی برای عاشقان قهوه و لذت بخش برای همه است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_151218148.png',
            price:89000,
            timeOfPreparation:10,
            slug:'coffee_brazilian',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:7,
            productId:41,
            productName:'قهوه آمریکانو',
            description:'قهوه اصلی ما با برندهای معتبر و طعم‌های متنوع، رویایی برای عاشقان قهوه و لذت بخش برای همه است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_151139360.png',
            price:99000,
            timeOfPreparation:10,
            slug:'coffee_americano',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:7,
            productId:42,
            productName:'قهوه تلخ',
            description:'قهوه اصلی ما با برندهای معتبر و طعم‌های متنوع، رویایی برای عاشقان قهوه و لذت بخش برای همه است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_151042194.png',
            price:69000,
            timeOfPreparation:10,
            slug:'coffee_bitter',
            discountAmount:13,
            discount: true,
        },
        {
            categoryId:7,
            productId:43,
            productName:'قهوه لته',
            description:'قهوه اصلی ما با برندهای معتبر و طعم‌های متنوع، رویایی برای عاشقان قهوه و لذت بخش برای همه است.',
            productImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/04/image_2024-04-13_150944732.png',
            price:69000,
            timeOfPreparation:10,
            slug:'coffee_bitter',
            discountAmount:13,
            discount: true,
        },

    ],
    comments:[
        {
            comment_id:0,
            userName:'بیتا محمدی',
            userImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/02/Ellipse-22-3.svg',
            comment:'کیفیت غذا هاخیلی خوب و طعمشون خیلی خوش مزه بود،این یه کامنت ساختگیه جهت چک کردن دیزان متن، استاد پارسا قربانیان دوست داریم.',
            userNameId:0,
        },
        {
            comment_id:1,
            userName:'محمود الهی',
            userImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/02/Ellipse-22-5.svg',
            comment:'کیفیت غذا هاخیلی خوب و طعمشون خیلی خوش مزه بود،این یه کامنت ساختگیه جهت چک کردن دیزان متن، استاد پارسا قربانیان دوست داریم.',
            userNameId:1,
        },
        {
            comment_id:2,
            userName:'سارا احمدی',
            userImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/02/Ellipse-22-4.svg',
            comment:'کیفیت غذا هاخیلی خوب و طعمشون خیلی خوش مزه بود،این یه کامنت ساختگیه جهت چک کردن دیزان متن، استاد پارسا قربانیان دوست داریم.',
            userNameId:2,
        },

    ],
    branches:[
        {
            branch_id:0,
            branchName:'اصفهان',
            branchImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/Frame-239.png',
            branchAddress:'ایران،اصفهان،میدان امام',
            branchNumber: '09123456789',
        },
        {
            branch_id:1,
            branchName:'تهران',
            branchImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/Frame-11156.png',
            branchAddress:'ایران،تهران،برج میلاد',
            branchNumber: '09123456789',
        },
        {
            branch_id:2,
            branchName:'شیراز',
            branchImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/01/Frame-11157.png',
            branchAddress:'ایران،شیراز،تخت جمشید',
            branchNumber: '09123456789',
        },
        {
            branch_id:3,
            branchName:'مشهد',
            branchImage:'https://ezteam.ir/toranj/wp-content/uploads/2024/03/image_2024-03-29_022457989.png',
            branchAddress:'ایران،مشهد،حرم مطهر رضوی',
            branchNumber: '09123456789',
        }
    ],
    socials:[
        {
            social_id:0,
            socialName:'ایکس',
            socialIcon:'fa-brands fa-x-twitter',
            socialLink:'https://x.com/?lang=en'
        },
        {
            social_id:1,
            socialName:'اینستاگرام',
            socialIcon:'fa-brands fa-instagram',
            socialLink:'https://www.instagram.com/'
        },
        {
            social_id:2,
            socialName:'تلگرام',
            socialIcon:'fa-brands fa-telegram',
            socialLink:'https://telegram.org/'
        },
        {
            social_id:3,
            socialName:'واتس اپ',
            socialIcon:'fa-brands fa-whatsapp',
            socialLink:'https://web.whatsapp.com'
        },
    ],
    services : [
        {
            service_id:0,
            serviceHeading:'خدمات پذیرایی',
            serviceDescription : 'خیلی سریع میتونی سفارشتو ثبت کنی و از خدمات پذیرایی رستوران استفاده کنی',
            serviceImage : 'https://ezteam.ir/toranj/wp-content/uploads/2024/01/Group-64.png'
        },
        {
            service_id:1,
            serviceHeading:'خدمات بیرون بر',
            serviceDescription : 'در اپلیکیشن ترخون میتونی سفارشتو به صورت بیرون بر ثبت کنی',
            serviceImage : 'https://ezteam.ir/toranj/wp-content/uploads/2024/01/Group-63.png'
        },
        {
            service_id:2,
            serviceHeading:'خدمات تحویل',
            serviceDescription : 'در سریع ترین زمان و با بهترین بسته بندی سفارشتو تحویل بگیر',
            serviceImage : 'https://ezteam.ir/toranj/wp-content/uploads/2024/01/Group-62.png'
        },
        {
            service_id:3,
            serviceHeading:'رزرو آنلاین',
            serviceDescription : 'در ترخون به صورت انلاین سفارش بده و در سریع ترین زمان تحویل بگیر',
            serviceImage : 'https://ezteam.ir/toranj/wp-content/uploads/2024/01/Group-61.png'
        },
    ]
}
export default sampleData;
